### ISSUE TITLE
Hb appstore couldn't connect to the internet

### ISSUE THREAD

**Issue by JadeInTheSky** [vgmoose/hb-appstore#83]
**Describe the bug**
Every time the hb appstore is launch, it goes straight into the couldn't connect to the internet page.
I tested on 2 modded switch, one works, the other doesn't. Every settings are the same, both switch are connected to the same internet, DNS are the same, not in flight mode or anything.

**Platform:**
Switch

**To Reproduce**
Launch atmosphère, goes into hb menu, launch hb appstore, goes straight to cannot connect to the internet  (console IS connected to internet)
![8ce7e5ed-b19c-4664-a184-4ca471488f89](https://user-images.githubusercontent.com/45185179/167653490-f4949ba5-218f-4054-9407-5552d16db748.jpg)

**Comment by vgmoose** [comment]
It's a shot in the dark, but the may issue have to do with a blocklist in the hosts file, if all other things are even: https://gbatemp.net/threads/switch-homebrew-appstore.493086/page-18#post-9658656

These file can be in `sd:/atmosphere/hosts/`, and some contain lines that look like:
```
switch*.*
*switch*.*
```
Which would match the domain:
```
switchbru.com
```

If this is it, then likely this error screen should be updated to be aware of [dns-mitm](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/dns_mitm.md), potentially even checking its regexes and warning the user.

If it's not a hosts file issue, I'd suggest trying an Internet-browsing DNS (like 45.55.142.122) to try and visit the web [Homebrew App store site at apps.fortheusers.org](https://apps.fortheusers.org), and see if that's also unreachable via the browser alone. If it can be reached in the browser and display apps from the repo, then it would demonstrate that it's not a networking problem.

**Comment by JadeInTheSky** [comment]
for a shot in the dark you got a bullzeye. it indeed had 

`switch*.*
 *switch*.*` <br>
and switchbrew in the host file. retracted them, cleared cache and now it works perfectly e
